/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "surface": "#f9f9fe",
        "surface-dim": "#d3dae9",
        "surface-bright": "#f9f9fe",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#f2f3fa",
        "surface-container": "#ebeef7",
        "surface-container-high": "#e4e8f3",
        "surface-container-highest": "#dce3f0",
        "surface-variant": "#dce3f0",
        "surface-tint": "#005bc1",
        "on-surface": "#2c333d",
        "on-surface-variant": "#595f6a",
        "on-background": "#2c333d",
        "background": "#f9f9fe",
        "primary": "#005bc1",
        "primary-dim": "#004faa",
        "primary-container": "#d8e2ff",
        "primary-fixed": "#d8e2ff",
        "primary-fixed-dim": "#c2d4ff",
        "on-primary": "#f7f7ff",
        "on-primary-container": "#004ea8",
        "on-primary-fixed": "#003d85",
        "on-primary-fixed-variant": "#0058bb",
        "secondary": "#5e5f63",
        "secondary-dim": "#525357",
        "secondary-container": "#e3e2e7",
        "secondary-fixed": "#e3e2e7",
        "secondary-fixed-dim": "#d5d4d9",
        "on-secondary": "#f9f8fe",
        "on-secondary-container": "#515156",
        "on-secondary-fixed": "#3e3f43",
        "on-secondary-fixed-variant": "#5b5b60",
        "tertiary": "#745c00",
        "tertiary-dim": "#665100",
        "tertiary-container": "#f5ce53",
        "tertiary-fixed": "#f5ce53",
        "tertiary-fixed-dim": "#e6c047",
        "on-tertiary": "#fff8ef",
        "on-tertiary-container": "#584500",
        "on-tertiary-fixed": "#413200",
        "on-tertiary-fixed-variant": "#634e00",
        "error": "#9f403d",
        "error-dim": "#4e0309",
        "error-container": "#fe8983",
        "on-error": "#fff7f6",
        "on-error-container": "#752121",
        "outline": "#747b86",
        "outline-variant": "#acb2bf",
        "inverse-surface": "#0c0e12",
        "inverse-on-surface": "#9c9da1",
        "inverse-primary": "#4b8eff",
      },
      fontFamily: {
        headline: ["Manrope", "Inter", "system-ui", "sans-serif"],
        body: ["Inter", "system-ui", "sans-serif"],
        label: ["Inter", "system-ui", "sans-serif"],
        sans: ["Inter", "system-ui", "sans-serif"],
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        "2xl": "1rem",
        "3xl": "1.5rem",
        full: "9999px",
      },
    },
  },
  plugins: [],
};